export const IMAGE = 'https://static2.evente.cn/static/img/icon.jpg';

export const ALT = '水滴';

export const TITLE = {
  Start: '快速开始',
  Log: '更新日志',
  Agreement: '开发约定',
  Affix: 'Affix 固钉',
  Badge: 'Badge 徽标数',
  Breadcrumb: 'Breadcrumb 面包屑',
  Button: 'Button 按钮',
  Cascader: 'Cascader 联级选择',
  Checkbox: 'Checkbox 多选',
  Calendar: 'Calendar 日历',
  DatePicker: 'DatePicker 日历选择器',
  Empty: 'Empty 空状态',
  Grid: 'Grid 栅格',
  Icon: 'Icon 图标',
  Input: 'Input 输入框',
  InputNumber: 'InputNumber 数字输入框',
  Link: 'Link 超链',
  Modal: 'Modal 对话框',
  Page: 'Page 分页',
  Popconfirm: 'Popconfirm 气泡确认框',
  Popover: 'Popover 气泡卡片',
  Radio: 'Radio 单选',
  Select: 'Select 选择器',
  Scroll: 'Scroll 滚动',
  Spin: 'Spin 加载中',
  Switch: 'Switch 开关',
  Timeline: 'Timeline 时间轴',
  Tag: 'Tag 标签',
  Table: 'Table 表格',
  Tooltip: 'Tooltip 文字提示',
  Progress: 'Progress 进度条',
};
